const select=document.querySelector("#asset-select"),viewer=document.querySelector("#qc-viewer"),status=document.querySelector("#load-status"),assetSize=document.querySelector("#asset-size");
const fields={assetId:document.querySelector("#asset-id"),route:document.querySelector("#route-badge"),materialFamily:document.querySelector("#material-family"),stage:document.querySelector("#current-stage"),currentStatus:document.querySelector("#current-status"),sourceCommit:document.querySelector("#source-commit"),glbPath:document.querySelector("#glb-path"),source:document.querySelector("#source-link"),author:document.querySelector("#author"),license:document.querySelector("#license-link"),structure:document.querySelector("#glb-structure"),integrity:document.querySelector("#integrity")};
let registry=[],activeAsset=null;
function setStatus(message,state){status.textContent=message;status.dataset.state=state;}
function formatBytes(bytes){const units=["B","KB","MB","GB"];let value=bytes,unit=0;while(value>=1024&&unit<units.length-1){value/=1024;unit+=1;}return `${value.toFixed(unit>1?1:0)} ${units[unit]}`;}
function applyLink(element,label,url){element.textContent=label;element.href=url;}
function updateInfo(asset){fields.assetId.textContent=asset.assetId;fields.route.textContent=asset.route;fields.materialFamily.textContent=asset.materialFamily;fields.stage.textContent=asset.stage;fields.currentStatus.textContent=asset.status;fields.sourceCommit.textContent=asset.sourceCommit.slice(0,12);fields.glbPath.textContent=asset.sourcePath;applyLink(fields.source,asset.sourceTitle||"Meshy Community",asset.sourceUrl);fields.author.textContent=asset.author;applyLink(fields.license,asset.license,asset.licenseUrl);fields.structure.textContent=`${asset.meshCount} meshes · ${asset.materialCount} materials · ${asset.imageCount} images`;fields.integrity.textContent=`SHA-256 verified · GLB v${asset.glbVersion}`;assetSize.textContent=formatBytes(asset.actualBytes);}
function resetCamera(){viewer.cameraTarget="auto auto auto";viewer.cameraOrbit="45deg 75deg auto";viewer.fieldOfView="30deg";viewer.jumpCameraToGoal();}
function autoFrame(){const orbit=viewer.getCameraOrbit();viewer.cameraTarget="auto auto auto";viewer.cameraOrbit=`${orbit.theta}rad ${orbit.phi}rad auto`;viewer.jumpCameraToGoal();}
function zoom(factor){if(!viewer.loaded)return;const orbit=viewer.getCameraOrbit(),nextRadius=Math.max(orbit.radius*factor,.001);viewer.cameraOrbit=`${orbit.theta}rad ${orbit.phi}rad ${nextRadius}m`;viewer.jumpCameraToGoal();}
function loadAsset(assetId){const asset=registry.find(candidate=>candidate.assetId===assetId);if(!asset)return;activeAsset=asset;updateInfo(asset);setStatus(`Loading ${asset.assetId}…`,"loading");viewer.alt=`${asset.assetId} interactive production GLB`;viewer.src=asset.modelUrl;const url=new URL(window.location.href);url.searchParams.set("asset",asset.assetId);history.replaceState(null,"",url);}
viewer.addEventListener("load",()=>{resetCamera();setStatus(`${activeAsset.assetId} loaded`,"loaded");document.documentElement.dataset.viewerReady="true";});
viewer.addEventListener("error",event=>{console.error("Model viewer error",event.detail);setStatus(`${activeAsset?.assetId||"Asset"} failed to load`,"error");document.documentElement.dataset.viewerReady="false";});
select.addEventListener("change",()=>loadAsset(select.value));document.querySelector("#reset-camera").addEventListener("click",resetCamera);document.querySelector("#auto-frame").addEventListener("click",autoFrame);document.querySelector("#zoom-in").addEventListener("click",()=>zoom(.8));document.querySelector("#zoom-out").addEventListener("click",()=>zoom(1.25));document.querySelectorAll(".view-preset").forEach(button=>button.addEventListener("click",()=>{viewer.cameraTarget="auto auto auto";viewer.cameraOrbit=button.dataset.orbit;viewer.jumpCameraToGoal();}));
async function boot(){try{await customElements.whenDefined("model-viewer");const response=await fetch("asset-registry.json",{cache:"no-store"});if(!response.ok)throw new Error(`Registry HTTP ${response.status}`);const payload=await response.json();registry=payload.assets;for(const route of ["RETEXTURE","DIRECT"]){const group=document.createElement("optgroup");group.label=route;registry.filter(asset=>asset.route===route).forEach(asset=>{const option=document.createElement("option");option.value=asset.assetId;option.textContent=asset.assetId;group.append(option);});select.append(group);}const requested=new URLSearchParams(location.search).get("asset"),initial=registry.some(asset=>asset.assetId===requested)?requested:"PROP_Chair_A";select.value=initial;loadAsset(initial);}catch(error){console.error(error);setStatus("Viewer initialization failed","error");}}
boot();
